spring.application.name=auth-service

spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}

spring.main.banner-mode=off

spring.jpa.show-sql=true
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update


secret=${SECRET_KEY}
expiration=3600000
server.port=8088

spring.security.user.name=user
spring.security.user.password=user