spring.application.name=customer-service

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}

spring.jpa.hibernate.ddl-auto=update
server.port=8081
spring.main.banner-mode=off
secret=${SECRET_KEY}