spring.application.name=customer-service

spring.datasource.url=jdbc:postgresql://localhost:5432/customer_service
spring.datasource.password=postgres
spring.datasource.username=postgres

spring.jpa.hibernate.ddl-auto=update
server.port=8081
spring.main.banner-mode=off