spring.application.name=car-service

spring.jpa.show-sql=true
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
server.port=8082
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=50
spring.main.banner-mode=off

secret=${SECRET_KEY}
