spring.application.name=car-service

spring.jpa.show-sql=true
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/car_service

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=50
springdoc.swagger-ui.path=/swagger-ui.html
spring.main.banner-mode=off